# Generated by Django 3.2.5 on 2021-11-30 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('calorific_value_in_kcal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommodityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('best_before_date', models.DateField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.commodity')),
            ],
        ),
    ]
